site_name: Pull Requests Robot
strict: true
repo_url: https://github.com/olegsu/pull-requests-robot
repo_name: olegsu/pull-requests-robot
use_directory_urls: false
theme:
  name: material
  language: en
  features:
    - navigation.tabs
markdown_extensions:
- attr_list
- codehilite
- admonition
- pymdownx.superfences
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.tabbed
- toc:
    permalink: true
nav:
  - Home: index.md
  - Privacy: privacy.md
