// Code generated by mockery v2.9.4. DO NOT EDIT.

package handlers

import mock "github.com/stretchr/testify/mock"

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: g
func (_m *MockOption) Execute(g *gh) {
	_m.Called(g)
}
