name: ci

on: [workflow_dispatch]

jobs:
  ci:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Test
      run: go test ./...
    - name: Build
      run: docker build -t $(cat docker-repository.txt):$(cat next_version) .

