name: ci

on: [workflow_dispatch]

jobs:
  ci:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
    - uses: actions/checkout@v2
    - name: Calculate Next Release Version
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} > token
        gh auth login --with-token < token
        last_pr=$(gh api -X GET search/issues -f q="repo:olegsu/pull-requests-robot is:closed is:pr sort:created-desc main" --jq '.items[0].number')
        if  [[ $last_pr = ""  ]]; then echo "No pull request found" && exit 1; fi;
        
        bump=$(gh pr view $last_pr --json labels --jq '.labels | map(select(.name | contains("release")) | .name) | .[0]')
        if ! [[ "$bump" =~ ^(release-minor|release-patch|release-major) ]]; then echo "Not a release commit" && exit 1; fi;        
        echo $bump > bump.txt
        
        current=$(gh release list | awk '{print $1}' | awk 'NR==1' | sed s/v//g)
        echo $current > version.txt 
        cat version.txt
        cat bump.txt