name: release

on: workflow_dispatch

jobs:
  release:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Build
      run: docker build -t $(cat docker-repository.txt):$(cat VERSION) .
    - name: Push
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker push $(cat docker-repository.txt):$(cat VERSION)
    - name: Update Cloud run
      run: gcloud run services update server --region us-central1 --image $(cat docker-repository.txt):$(cat VERSION)

