name: release

on:
  push:
    branches: [ 'main' ]

concurrency: server-release

jobs:
  release:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - name: Calculate Next Release Version
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} > token
        gh auth login --with-token < token
        go install github.com/davidrjonas/semver-cli@latest
        last_pr=$(gh pr list -s merged --json number,mergedAt -q '. |= sort_by(.mergedAt) | .[-1].number')
        bump=$(gh pr view --json labels --jq '.labels | map(select(.name | contains("release")) | .name) | .[0]')
        if ! [[ "$bump" =~ ^(release-minor|release-patch|release-major) ]]; then echo "Not a release commit" && exit 0; fi;        
        current=$(gh release list | awk '{print $1}' | awk 'NR==1' | sed s/v//g)
        semver-cli inc $(echo $bump | sed s/release-//g) $current > next_version
        echo "next version: $(cat next_version)"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Build
      run: docker build -t $(cat docker-repository.txt):$(cat next_version) .
    - name: Push
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker push $(cat docker-repository.txt):$(cat next_version)
    - name: Update Cloud run
      run: gcloud run services update server --region us-central1 --image $(cat docker-repository.txt):$(cat next_version)
    - name: Release
      run: gh release create v$(cat next_version)

